phrase = "Awana Academy"
print("Awana\nAcademy")
print("Awana\"Academy")
print("Awana\Academy")
print(phrase + " is cool")
print(phrase.capitalize())
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("A"))
print(phrase.index("na"))
print(phrase.replace("Awana", "Diamondtia" ))